### ISSUE TITLE
Kort of lang menu

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/visitatie#2]
https://github.com/fdnd/visitatie/blob/14827a66eedd25c53c3e243938c2b0d50398d520/index.html#L26

Korte menu labels
Of
Lange menu labels

https://github.com/fdnd/visitatie/blob/14827a66eedd25c53c3e243938c2b0d50398d520/inleiding.html#L26

**Comment by ju5tu5** [comment]
Korte, is al doorgevoerd
