### ISSUE TITLE
Bestandsnamen

### ISSUE THREAD

**Issue by ju5tu5** [fdnd/visitatie#6]
Titels van alle downloads zijn niet netjes. We moeten de spaties weghalen en links aanpassen..

**Comment by KoopReynders** [comment]
Bad value for attribute href. 

Unexpected character Macrodoelmatigheid Ad Frontend Design & Developme in path href='/assets/visitatie/Aanvraag Macrodoelmatigheid Ad F' href='/assets/visitatie/Besluit macrodoelmatigheid met a' href='/assets/visitatie/Enquête werkveldonderzoek (Res'href='/assets/visitatie/Werkveldsessie beroeps- en oplei' https://visitatie.fdnd.nl/  Line 66 67 68 70 |  

Unexpected character 01_Leerresultaten.pdf in path href='/assets/docs/Bijlage 01_Leerresultaten.pdf' href='/assets/docs/Bijlage 02_Typering taken MBO-4, Asso'href='/assets/docs/Bijlage 03_Beroeps- en opleidingsprof' href='/assets/docs/Bijlage 04_Leerplanschema.pdf' href='/assets/docs/Bijlage 05_Studiegids.pdf' https://visitatie.fdnd.nl/kerndocumenten.html

**Comment by ju5tu5** [comment]
Fixed (denk ik)
